sudo: false
language: ruby
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - '2.0'
  - 2.1
  - 2.2
  - 2.3
  - jruby-18mode
  - jruby-19mode
  - jruby-9.0.4.0
env:
  - BUNDLE_WITHOUT=secondary:development
  - BUNDLE_WITHOUT=primary:development

matrix:
  allow_failures:
    - env: BUNDLE_WITHOUT=primary:development
